knpu_oauth2_client:
  clients:
    vk_main:
      type: vkontakte
      client_id: '%env(OAUTH_VK_ID)%'
      client_secret: '%env(OAUTH_VK_SECRET)%'
      redirect_route: oauth.vk.check
      redirect_params: {}
      # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration